# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: Unlicense

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
    exclude: |
      (?x)^(
        lib/|
        ports/espressif/components/bootloader/subproject/components
      )
  - id: end-of-file-fixer
    exclude: |
      (?x)^(
        lib/|
        .idea/
      )

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    args: [-w]
    exclude: |
      (?x)^(
        lib/
      )
